export default {
    GET_FILM_PERSONS: "GET_FILM_PERSONS",
    GET_FILM_PERSONS_FULFILLED: "GET_FILM_PERSONS_FULFILLED",
    GET_FILM_PERSON: "GET_FILM_PERSON",
    GET_FILM_PERSON_FULFILLED: "GET_FILM_PERSON_FULFILLED",
    POST_FILM_PERSON: "POST_FILM_PERSON",
    POST_FILM_PERSON_FULFILLED: "POST_FILM_PERSON_FULFILLED",
    PATCH_FILM_PERSON: "PATCH_FILM_PERSON",
    PATCH_FILM_PERSON_FULFILLED: "PATCH_FILM_PERSON_FULFILLED",
    RESET_FILM_PERSON: "RESET_FILM_PERSON"
};
