export default {
    GET_FILMS: "GET_FILMS",
    GET_FILMS_FULFILLED: "GET_FILMS_FULFILLED",
    GET_FILM: "GET_FILM",
    GET_FILM_FULFILLED: "GET_FILM_FULFILLED",
    POST_FILM: "POST_FILM",
    POST_FILM_FULFILLED: "POST_FILM_FULFILLED",
    PATCH_FILM: "PATCH_FILM",
    PATCH_FILM_FULFILLED: "PATCH_FILM_FULFILLED",
    DELETE_FILM: "DELETE_FILM",
    DELETE_FILM_FULFILLED: "DELETE_FILM_FULFILLED",
    GET_FILM_ROLES: "GET_FILM_ROLES",
    GET_FILM_ROLES_FULFILLED: "GET_FILM_ROLES_FULFILLED",
    RESET_FILM: "RESET_FILM"
};
